# -*- coding: utf-8 -*-
"""class06_image_smoothing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lh6sjRTX-0Xp3b7u7VwgIQCyRcn3-4Fm

## Image Smoothing and Blurring
"""

# This code was based on
# http://pyimagesearch.com/2021/04/28/opencv-smoothing-and-blurring/


import cv2
#import numpy as np
from matplotlib import pyplot as plt

"""## Average Blurring"""

###################  AVERAGE BLURRING ###################

# Read the image

image_path = "./images/cat.jpg"

image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Initialize a list of
# kernel sizes (so we can evaluate the relationship between kernel
# size and amount of blurring)
kernelSizes = [(5, 5), (17, 17), (25, 25)]

plt.figure()
plt.subplot(2,2,1),plt.imshow(image)
plt.title('Original Image')
plt.xticks([]),plt.yticks([])

i = 1
# loop over the kernel sizes
for (kX, kY) in kernelSizes:
	# apply an "average" blur to the image using the current kernel
	# size

	blurred = cv2.blur(image, (kX, kY))
	plt.subplot(2,2,i+1)
	plt.imshow(blurred)
	plt.title("Average ({}, {})".format(kX, kY))
	plt.xticks([]),plt.yticks([])
	i = i + 1

"""## Gaussian Blurring"""

###################  GAUSSIAN BLURRING ###################



# Read the image

image_path = "./images/butterfly.jpg"

image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Initialize a list of
# kernel sizes (so we can evaluate the relationship between kernel
# size and amount of blurring)
kernelSizes = [(5, 5), (17, 17), (25, 25)]

plt.figure()
plt.subplot(2,2,1),plt.imshow(image)
plt.title('Original Image')
plt.xticks([]),plt.yticks([])
i = 1
# loop over the kernel sizes
for (kX, kY) in kernelSizes:
	# apply an "average" blur to the image using the current kernel
	# size

	blurred = cv2.GaussianBlur(image, (kX, kY), 0)
	plt.subplot(2,2,i+1)
	plt.imshow(blurred)
	plt.title("Gaussian ({}, {})".format(kX, kY))
	plt.xticks([]),plt.yticks([])
	i = i + 1


plt.show()