# -*- coding: utf-8 -*-
"""class06_morphological_operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9tXeLik-AQ8AwFFDv-j161ow52L4YN1

## Morphological Operations
"""

# This code was based on:
# https://docs.opencv.org/4.x/d9/d61/tutorial_py_morphological_ops.html

import cv2
import numpy as np
from matplotlib import pyplot as plt


image_file = './images/stuff.jpg'
SHOW_OPENCV = False

"""## Let's first do image blurring and binarization"""

img = cv2.imread(image_file, cv2.IMREAD_GRAYSCALE)
assert img is not None, "file could not be read"

# Apply Gaussian Blur to reduce noise
blur = cv2.GaussianBlur(img, (3, 3), 0)
ret,img_th = cv2.threshold(img,127,255,cv2.THRESH_BINARY)

fig = plt.figure()
plt.imshow(img_th,'gray')
plt.title('Binary Image')
plt.xticks([]),plt.yticks([])


if SHOW_OPENCV == True:
  # Display result
  cv2.namedWindow("Binary Image",cv2.WINDOW_NORMAL)
  cv2.imshow("Binary Image", img_th)

"""## Dilation"""

####### Dilation ###############

# Defining kernel
kernel = np.ones((5,5),dtype=np.uint8)

# Applying dilation operation
img_dilate = cv2.dilate(img_th, kernel, iterations=2)

fig = plt.figure()
plt.imshow(img_dilate,'gray')
plt.title('Image Dilation')
plt.xticks([]),plt.yticks([])


if SHOW_OPENCV == True:
  # Display result
  cv2.namedWindow("Image Dilation",cv2.WINDOW_NORMAL)
  cv2.imshow("Image Dilation", img_dilate)

"""## Erosion"""

# Defining kernel
kernel = np.ones((5,5),dtype=np.uint8)


# Applying dilation operation
img_erode = cv2.erode(img_th, kernel, iterations=2)

fig = plt.figure()
plt.imshow(img_erode,'gray')
plt.title('Image Erosion')
plt.xticks([]),plt.yticks([])


if SHOW_OPENCV == True:
  # Display result
  cv2.namedWindow("Image Erosion",cv2.WINDOW_NORMAL)
  cv2.imshow("Image Erosion", img_erode)

"""## Opening"""

# Defining kernel
kernel = np.ones((5,5),np.uint8)

# Applying opening operation
img_open = cv2.morphologyEx(img_th, cv2.MORPH_OPEN, kernel, iterations=2)

fig = plt.figure()
plt.imshow(img_open,'gray')
plt.title('Image Opening')
plt.xticks([]),plt.yticks([])


if SHOW_OPENCV == True:
  # Display result
  cv2.namedWindow("Image Opening",cv2.WINDOW_NORMAL)
  cv2.imshow("Image Opening", img_open)

"""## Closing"""

# Defining kernel
kernel = np.ones((5,5),np.uint8)

# Applying closing operation
img_close = cv2.morphologyEx(img_th, cv2.MORPH_CLOSE, kernel, iterations=2)

fig = plt.figure()
plt.imshow(img_close,'gray')
plt.title('Image Closing')
plt.xticks([]),plt.yticks([])


if SHOW_OPENCV == True:
  # Display result
  cv2.namedWindow("Image Closing",cv2.WINDOW_NORMAL)
  cv2.imshow("Image Closing", img_close)

"""## Morphological Gradient"""

# Defining kernel
kernel = np.ones((5,5),np.uint8)

# Applying  operation
img_grad = cv2.morphologyEx(img_th, cv2.MORPH_GRADIENT, kernel)

fig = plt.figure()
plt.imshow(img_grad,'gray')
plt.title('Morphological Gradient')
plt.xticks([]),plt.yticks([])
plt.show()

if SHOW_OPENCV == True:
  # Display result
  cv2.namedWindow("Morphological Gradient",cv2.WINDOW_NORMAL)
  cv2.imshow("Morphological Gradient", img_grad)
  cv2.waitKey(0)
  cv2.destroyAllWindows()